### ISSUE TITLE
一些无关紧要的格式问题

### ISSUE THREAD

**Issue by kokic** [SimplicialCat/topos#1]
$\text{Page 5.}$ 根据其含义, $\text{nLab}$ 建议改为 $n\text{Lab}$.
$\text{Page 17.}$ 命题 $1.1.25$, 是否有考虑将交换图改为行间显示以避免 "因此" 前的意外分段? 另一可取的选择是将图变小以适合行内文本的排布. 
$\text{Page 20.}$ 自然同构部分的 `aligned` 环境可以改为在同构符号后对齐, 即 

$$\begin{aligned}
            &~ \text{Hom}_\mathsf{C}\\,(W,\Pi_X~(f)) \\
\simeq &~ \big\\{ ~ h:W\to Z^X \\;|\\; f^X \circ h = \text{id}_X \circ W ~ \big\\} \\
\simeq &~ \big\\{ ~ h:W \times X \to Z \\;|\\; f \circ h = \text{pr}_2: W \times X \to X ~ \big\\} \\ 
\simeq &~ \text{Hom} _{\mathsf{C}/X}\\,(X^*W,f).
\end{aligned}$$ 

$\text{Page 53.}$ "到空间 $X$ 的平展态射" 前的断行是否有特殊内涵?

**Comment by SimplicialCat** [comment]
谢谢, 已修改.
